#dataset parameters
experiment: "kasthuri_pp"
num_classes: 1
class_names: "mito"

#set the paths for data directories, models, and pretrained weights
data_path: "../data/${experiment}/"
model_path: "../models/${experiment}/"
pretraining: "/data/IASEM/conradrw/models/MoCoV2_224_Unfiltered/current.pth.tar" #imagenet or none

#hyperparameters
lr: 3e-3
wd: 0.1
iters: 5000
bsz: 16
lr_policy: "OneCycle"
optim: "AdamW"
crop_size: 512
finetune_layer: "none"
freeze_bn: "false"
jobs: 4

#set pixel norm values
norms:
    mean: 0.27342241
    stdev: 0.26917548