#dataset parameters
experiment: "perez_nucleoli"
data_path: "/data/IASEM/conradrw/data/benchmarks/guay/2d/"
num_classes: 1
class_names: "nucleoli"

#hyperparameters
lr: 3e-3
wd: 0.1
iters: 5000
bsz: 16
lr_policy: "OneCycle"
optim: "AdamW"
crop_size: 480
finetune_layer: "none"
save_path: "/data/IASEM/conradrw/models/benchmark/${experiment}/${source}/${1}_unet_1cycle_${iters}_iters_df_${data_frac}_ft_${finetune_layer}_${5}.pth"
freeze_bn: "false"

#pretrained weights file
pretraining: "/data/IASEM/conradrw/models/MoCoV2_224_Unfiltered/current.pth.tar" #imagenet, none