# training parameters
experiment_name: "SWaV_CEM1.5M"
data_path: "/data/IASEM/conradrw/data/cem_datasets/v1_cem/cem1.4M/"
model_path: "/data/IASEM/conradrw/models/SWaV_cem1.4M/"

print_freq: 1

arch: "resnet50"
hidden_mlp: 2048
workers: 16
checkpoint_freq: 25
use_fp16: True
seed: 1447
resume: null

epochs: 400
warmup_epochs: 0
start_warmup: 0
batch_size: 64
base_lr: 0.015
final_lr: 0.0006
wd: 0.000001
freeze_prototypes_niters: 5005

# distributed training parameters
world_size: 1
rank: 0
dist_url: "tcp://localhost:10001"
dist_backend: "nccl"
multiprocessing_distributed: True

# SWaV parameters
nmb_crops:
  - 2
  - 6
size_crops:
  - 224
  - 96
min_scale_crops:
  - 0.14
  - 0.05
max_scale_crops:
  - 1. 
  - 0.14
crops_for_assign:
  - 0
  - 1
temperature: 0.1
epsilon: 0.05
sinkhorn_iterations: 3
feat_dim: 128
nmb_prototypes: 3000
queue_length: 3840
epoch_queue_starts: 15

norms:
  - 0.58331613
  - 0.09966064
