#basic definitions
experiment_name: "CellEMNet_MoCoV2"
data_file: "/data/IASEM/conradrw/data/images224/images224_fpaths_filtered.npz"
model_dir: "/data/IASEM/conradrw/models/CellEMNet_MoCoV2/"
arch: "resnet50"
workers: 16
epochs: 200
save_freq: 20
print_freq: 10
batch_size: 128
lr: 0.015
schedule:
  - 120
  - 160
momentum: 0.9
weight_decay: 0.0001

resume: ""
world_size: 1
rank: 0
dist_url: "tcp://224.66.41.62:2345"
dist_backend: "nccl"
multiprocessing_distributed: True

moco_dim: 128
moco_k: 65536
moco_m: 0.999
moco_t: 0.2

mlp: True
cos: False
logging: True

norms:
    mean: 0.76752738
    std: 0.10404078