#basic definitions
experiment_name: "CEM500K_PixPro100"
data_dir: "/data/IASEM/conradrw/data/cem500k/" # a .npz dask array of filepaths
model_dir: "/data/IASEM/conradrw/models/CEM500K_PixPro100/" # the directory in which to save model states
arch: "resnet50"
workers: 32
start_epoch: 0
epochs: 100
save_freq: 20
print_freq: 10
batch_size: 512
lr: 2
momentum: 0.9
weight_decay: 0.00001
logging: True

resume: ""
world_size: 1
rank: 0
dist_url: "tcp://localhost:10001"
dist_backend: "nccl"
multiprocessing_distributed: True

pixpro_mom: 0.9934
ppm_layers: 1
ppm_gamma: 2 
pixpro_t: 0.7

fp16: True

norms:
    mean: 0.58331613
    std: 0.09966064
